from setuptools import setup, find_packages
from hypermapper import __version__

setup(
    name='HyperMapp3r',
    version=__version__,
    description='A CNN-based segmentation technique using MRI images from BrainLab',
    author=['Maged Goubran', 'Parisa Mojiri', 'Edward Ntiri'],
    author_email='maged.goubran@sri.utoronto.ca',
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    license='GNU GENERAL PUBLIC LICENSE v3',
    url='https://github.com/mgoubran/HyperMapp3r',  # change later
    download_url='https://github.com/mgoubran/HyperMapp3r',
    long_description=open('README.md').read(),
    classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Environment :: Console',
        'Environment :: X11 Applications :: Qt',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: GNU  General Public License v3 (GPLv3)',
        'Operating System :: POSIX :: Linux',
        'Operating System :: MacOS',
        'Operating System :: Unix',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Unix Shell',
        'Topic :: Scientific/Engineering',
        'Topic :: Scientific/Engineering :: Medical Science Apps.',
        'Topic :: Scientific/Engineering :: Bio-Informatics',
        'Topic :: Scientific/Engineering :: Image Recognition',
    ],
    install_requires=[
        'argcomplete', 
        'argparse',
        'joblib',
        'keras==2.11', 
        'nibabel', 
        'nilearn', 
        'nipype', 
        'numpy', 
        'pandas', 
        'plotly', 
        'PyQt5', 
        'scikit-learn',
        'tensorflow_addons=0.19.0', 
        'termcolor'
    ],
    extras_require={
        "hypermapper": ["tensorflow==2.11"],
        "hypermapper-gpu": ["tensorflow-gpu==2.11"],
    },
    entry_points={'console_scripts': ['hypermapper=hypermapper.cli:main']},
    keywords=[
        'neuroscience dementia lesion stroke white-matter-hyperintensity brain-atlas mri neuroimaging',
        'medical-imaging biomedical image-processing image-registration image-segmentation',
    ],
)
